# Generated by Django 4.1.3 on 2022-12-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_event_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
