# Generated by Django 4.1.3 on 2022-12-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("time", models.DateTimeField()),
                ("count", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("name_id", models.CharField(blank=True, max_length=200, null=True)),
                ("account", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Mem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("count", models.CharField(blank=True, max_length=200, null=True)),
                ("food", models.CharField(blank=True, max_length=200, null=True)),
                ("job", models.CharField(blank=True, max_length=200, null=True)),
                ("residence", models.CharField(blank=True, max_length=200, null=True)),
                ("stature", models.CharField(blank=True, max_length=200, null=True)),
                ("age", models.CharField(blank=True, max_length=200, null=True)),
                ("weight", models.CharField(blank=True, max_length=200, null=True)),
                ("muscle", models.CharField(blank=True, max_length=200, null=True)),
                ("fat", models.CharField(blank=True, max_length=200, null=True)),
                ("hope_time", models.TextField(blank=True, null=True)),
                ("health_career", models.TextField(blank=True, null=True)),
                ("note1", models.TextField(blank=True, null=True)),
                ("note2", models.TextField(blank=True, null=True)),
                ("account", models.CharField(max_length=200)),
            ],
        ),
    ]
