# Generated by Django 4.1.3 on 2023-01-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
