# Generated by Django 4.1.3 on 2022-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="name", field=models.CharField(max_length=200),
        ),
    ]
