# Generated by Django 4.1.3 on 2022-12-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0002_alter_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="count",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
