# Generated by Django 4.1.3 on 2023-01-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0002_mem_phone_alter_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
