# Generated by Django 4.1.3 on 2023-01-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0003_alter_mem_end_date_alter_mem_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="date",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
