# Generated by Django 4.1.3 on 2023-01-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0004_mem_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="class_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="class_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="health_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="health_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="membership_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="membership_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="payment",
            field=models.CharField(
                choices=[("카드", "카드"), ("현금", "현금"), ("이체", "이체")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mem",
            name="resist_category",
            field=models.CharField(
                choices=[("워크인", "워크인"), ("재등록", "재등록"), ("SNS", "SNS"), ("OT", "OT")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mem",
            name="account",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
