# Generated by Django 4.1.3 on 2023-01-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0005_mem_class_end_date_mem_class_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="empty1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="empty2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="empty3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="empty4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="empty5",
            field=models.TextField(blank=True, null=True),
        ),
    ]
