# Generated by Django 4.1.3 on 2023-01-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0006_mem_empty1_mem_empty2_mem_empty3_mem_empty4_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="empty1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="empty2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="empty3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="empty4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="empty5",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
