# Generated by Django 4.1.3 on 2023-01-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0007_alter_mem_empty1_alter_mem_empty2_alter_mem_empty3_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="mem", old_name="empty1", new_name="empty",),
        migrations.RemoveField(model_name="mem", name="empty2",),
        migrations.RemoveField(model_name="mem", name="empty3",),
        migrations.RemoveField(model_name="mem", name="empty4",),
        migrations.RemoveField(model_name="mem", name="empty5",),
    ]
