# Generated by Django 4.1.3 on 2023-01-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0008_rename_empty1_mem_empty_remove_mem_empty2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empty1", models.CharField(blank=True, max_length=200, null=True)),
                ("empty2", models.CharField(blank=True, max_length=200, null=True)),
                ("empty3", models.CharField(blank=True, max_length=200, null=True)),
                ("empty4", models.CharField(blank=True, max_length=200, null=True)),
                ("empty5", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(model_name="mem", old_name="empty", new_name="empty1",),
        migrations.AddField(
            model_name="mem",
            name="empty2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="empty3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="empty4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="empty5",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
