# Generated by Django 4.1.3 on 2023-01-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0009_option_rename_empty_mem_empty1_mem_empty2_mem_empty3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="account",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="count",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
