# Generated by Django 4.1.3 on 2023-01-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0010_option_account_option_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem", name="empty1", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mem", name="empty2", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mem", name="empty3", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mem", name="empty4", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mem", name="empty5", field=models.BooleanField(default=False),
        ),
    ]
