# Generated by Django 4.1.3 on 2023-01-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0011_alter_mem_empty1_alter_mem_empty2_alter_mem_empty3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="alarm",
            field=models.TextField(blank=True, null=True),
        ),
    ]
