# Generated by Django 4.1.3 on 2023-01-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0012_mem_alarm"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="alarm_check",
            field=models.BooleanField(default=False),
        ),
    ]
