# Generated by Django 4.1.3 on 2023-01-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0013_mem_alarm_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
