# Generated by Django 4.1.3 on 2023-01-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0014_mem_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
    ]
