# Generated by Django 4.1.3 on 2023-01-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0015_alter_mem_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cancel",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="cancel_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
