# Generated by Django 4.1.3 on 2023-01-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0016_event_cancel_event_cancel_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cancel",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
