# Generated by Django 4.1.3 on 2023-01-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0017_alter_event_cancel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="payment",
            field=models.CharField(
                choices=[("카드", "카드"), ("현금", "현금"), ("이체", "이체")],
                default="",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mem",
            name="resist_category",
            field=models.CharField(
                choices=[("워크인", "워크인"), ("재등록", "재등록"), ("SNS", "SNS"), ("OT", "OT")],
                default="",
                max_length=3,
                null=True,
            ),
        ),
    ]
