# Generated by Django 4.1.3 on 2023-01-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0020_alter_mem_payment_alter_mem_resist_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="payment",
            field=models.CharField(
                blank=True,
                choices=[("카드", "카드"), ("현금", "현금"), ("이체", "이체")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="mem",
            name="resist_category",
            field=models.CharField(
                blank=True,
                choices=[("워크인", "워크인"), ("재등록", "재등록"), ("SNS", "SNS"), ("OT", "OT")],
                max_length=3,
            ),
        ),
    ]
