# Generated by Django 4.1.3 on 2023-01-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0022_alter_mem_payment_alter_mem_resist_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="photo",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]
