# Generated by Django 4.1.3 on 2023-01-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0023_alter_mem_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="money",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
