# Generated by Django 4.1.3 on 2023-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0024_mem_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="money",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
