# Generated by Django 4.1.3 on 2023-01-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0025_alter_mem_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem", name="re_data", field=models.TextField(blank=True),
        ),
    ]
