# Generated by Django 4.1.3 on 2023-01-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0026_mem_re_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="option", name="count_money", field=models.TextField(blank=True),
        ),
    ]
