# Generated by Django 4.1.3 on 2023-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0027_option_count_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="count",
            field=models.CharField(
                blank=True, choices=[("", "")], max_length=200, null=True
            ),
        ),
    ]
