# Generated by Django 4.1.3 on 2023-01-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0028_alter_mem_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="count",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("", ""), ("", ""), ("", ""), ("", "")],
                max_length=200,
                null=True,
            ),
        ),
    ]
