# Generated by Django 4.1.3 on 2023-01-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0029_alter_mem_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="count",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
