# Generated by Django 4.1.3 on 2023-01-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0030_alter_mem_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="mem", name="photo",),
    ]
