# Generated by Django 4.1.3 on 2023-01-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0031_remove_mem_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="age",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="food",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("o", "o"), ("x", "x")],
                default="",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="mem",
            name="stature",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
