# Generated by Django 4.1.3 on 2023-01-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0032_alter_mem_age_alter_mem_food_alter_mem_stature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="age",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="mem",
            name="stature",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
