# Generated by Django 4.1.3 on 2023-01-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0035_alter_mem_age_alter_mem_money_alter_mem_stature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="money",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="stature",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
