# Generated by Django 4.1.3 on 2023-01-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0036_alter_mem_age_alter_mem_money_alter_mem_stature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mem",
            name="hope_time",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
