# Generated by Django 4.1.3 on 2023-02-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0037_alter_mem_hope_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="end_alarm",
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="option",
            name="end_alarm_cb",
            field=models.BooleanField(default=False),
        ),
    ]
