# Generated by Django 4.1.3 on 2023-02-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0039_alter_option_end_alarm"),
    ]

    operations = [
        migrations.RemoveField(model_name="option", name="end_alarm",),
        migrations.RemoveField(model_name="option", name="end_alarm_cb",),
    ]
