# Generated by Django 4.1.3 on 2023-02-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0040_remove_option_end_alarm_remove_option_end_alarm_cb"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="end_alarm",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="option",
            name="end_alarm_cb",
            field=models.BooleanField(default=False),
        ),
    ]
