# Generated by Django 4.1.3 on 2023-02-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0041_option_end_alarm_option_end_alarm_cb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="end_alarm",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
