# Generated by Django 4.1.3 on 2023-02-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0042_alter_option_end_alarm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="end_alarm",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
