# Generated by Django 4.1.3 on 2023-02-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0043_alter_option_end_alarm"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="start_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mem",
            name="resist_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("워크인", "워크인"),
                    ("재등록", "재등록"),
                    ("SNS", "SNS"),
                    ("OT", "OT"),
                    ("인계", "인계"),
                ],
                default="",
                max_length=3,
            ),
        ),
    ]
