# Generated by Django 4.1.3 on 2022-12-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0004_event_name_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mem",
            name="age",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="count",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="fat",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="food",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="health_career",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="hope_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="job",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="muscle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="note1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="note2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="residence",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="stature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mem",
            name="weight",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
